"""Depolama arayüzü. SQL yalnızca `storage/` içinde yazılır; diğer paketler bu protokolü kullanır.

Faz 0 kapsamı: heartbeat, collector sağlığı, outbox, ayarlar, DB boyutu. Sonraki fazlar
metotları genişletir; TimescaleDB geçişi yeni bir implementasyonla yapılır (ARCHITECTURE.md §20).
"""

from datetime import datetime
from typing import Any, Protocol

from marketpulse.storage.models import CollectorHealth, Heartbeat, OutboxEvent


class Repository(Protocol):
    async def create_all(self) -> None:
        """Tabloları metadata'dan oluşturur (test ve geliştirme; üretimde Alembic)."""
        ...

    async def close(self) -> None: ...

    # --- engine heartbeat ---
    async def write_heartbeat(self, ts: datetime, version: str) -> None: ...
    async def read_heartbeat(self) -> Heartbeat | None: ...
    async def clear_heartbeat(self) -> None: ...

    # --- collector sağlığı ---
    async def upsert_collector_health(self, health: CollectorHealth) -> None: ...
    async def list_collector_health(self) -> list[CollectorHealth]: ...

    # --- outbox ---
    async def outbox_emit(
        self, topic: str, payload: dict[str, Any], created_at: datetime
    ) -> int: ...
    async def outbox_read_after(self, last_id: int, limit: int = 500) -> list[OutboxEvent]: ...
    async def outbox_max_id(self) -> int: ...
    async def outbox_prune(self, before: datetime) -> int: ...

    # --- ayarlar ---
    async def get_setting(self, key: str) -> Any | None: ...
    async def set_setting(self, key: str, value: Any, updated_at: datetime) -> None: ...

    # --- meta ---
    async def db_size_bytes(self) -> int | None: ...
