/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Health */
    get: operations['get_health_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** CollectorHealthOut */
    CollectorHealthOut: {
      /** Collector */
      collector: string
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded' | 'down' | 'disabled' | 'budget_exhausted'
      /** Last Success At */
      last_success_at: string | null
      /** Last Error At */
      last_error_at: string | null
      /** Last Error */
      last_error: string | null
      /** Consecutive Failures */
      consecutive_failures: number
    }
    /** DbHealthOut */
    DbHealthOut: {
      /** Size Bytes */
      size_bytes: number | null
    }
    /** EngineHealthOut */
    EngineHealthOut: {
      /** Alive */
      alive: boolean
      /** Last Heartbeat */
      last_heartbeat: string | null
      /** Age Seconds */
      age_seconds: number | null
      /** Version */
      version: string | null
    }
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded' | 'down'
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
      /** Api Version */
      api_version: string
      engine: components['schemas']['EngineHealthOut']
      /** Collectors */
      collectors: components['schemas']['CollectorHealthOut'][]
      db: components['schemas']['DbHealthOut']
      outbox: components['schemas']['OutboxHealthOut']
      ws: components['schemas']['WsHealthOut']
    }
    /** OutboxHealthOut */
    OutboxHealthOut: {
      /** Last Id */
      last_id: number
      /** Last Event At */
      last_event_at: string | null
      /** Lag Seconds */
      lag_seconds: number | null
    }
    /** WsHealthOut */
    WsHealthOut: {
      /** Clients */
      clients: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_health_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
