"""initial

Revision ID: 0001
Revises:
Create Date: 2026-09-15 15:23:37.402363+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("dedup_key", sa.String(length=128), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index("ix_alerts_acknowledged_at", ["acknowledged_at"], unique=False)
        batch_op.create_index("ix_alerts_created_at", ["created_at"], unique=False)

    op.create_table(
        "calendar_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
    )
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index("ix_calendar_events_scheduled_at", ["scheduled_at"], unique=False)

    op.create_table(
        "calibration_bins",
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("subset", sa.String(length=16), nullable=False),
        sa.Column("bin", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("mean_p", sa.Float(), nullable=True),
        sa.Column("observed_freq", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("horizon", "subset", "bin", name=op.f("pk_calibration_bins")),
    )
    op.create_table(
        "candles",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("interval", sa.String(length=4), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("quote_volume", sa.Float(), nullable=False),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base", sa.Float(), nullable=False),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "interval", "open_time", name=op.f("pk_candles")),
    )
    with op.batch_alter_table("candles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_candles_symbol_interval_close_time",
            ["symbol", "interval", "close_time"],
            unique=False,
        )

    op.create_table(
        "collector_health",
        sa.Column("collector", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("collector", name=op.f("pk_collector_health")),
    )
    op.create_table(
        "engine_heartbeat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engine_heartbeat")),
    )
    op.create_table(
        "events_outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("topic", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events_outbox")),
    )
    with op.batch_alter_table("events_outbox", schema=None) as batch_op:
        batch_op.create_index("ix_events_outbox_created_at", ["created_at"], unique=False)

    op.create_table(
        "fear_greed",
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_fear_greed")),
    )
    op.create_table(
        "funding_live",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_rate", sa.Float(), nullable=False),
        sa.Column("next_funding_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mark_price", sa.Float(), nullable=True),
        sa.Column("index_price", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "ts", name=op.f("pk_funding_live")),
    )
    op.create_table(
        "funding_rates",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("funding_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("mark_price", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "funding_time", name=op.f("pk_funding_rates")),
    )
    op.create_table(
        "liquidations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("side", sa.String(length=5), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_liquidations")),
    )
    with op.batch_alter_table("liquidations", schema=None) as batch_op:
        batch_op.create_index("ix_liquidations_symbol_ts", ["symbol", "ts"], unique=False)

    op.create_table(
        "llm_budget_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("spent_usd", sa.Float(), nullable=False),
        sa.Column("tier2_disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tier1_disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_budget_state")),
    )
    op.create_table(
        "llm_usage",
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("calls", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("date", "model", "tier", name=op.f("pk_llm_usage")),
    )
    op.create_table(
        "long_short_ratio",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("long_ratio", sa.Float(), nullable=False),
        sa.Column("short_ratio", sa.Float(), nullable=False),
        sa.Column("ratio", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "ts", "kind", name=op.f("pk_long_short_ratio")),
    )
    op.create_table(
        "macro_daily",
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "date", name=op.f("pk_macro_daily")),
    )
    op.create_table(
        "metrics_daily",
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("subset", sa.String(length=16), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("brier", sa.Float(), nullable=True),
        sa.Column("brier_skill", sa.Float(), nullable=True),
        sa.Column("hit_rate", sa.Float(), nullable=True),
        sa.Column("base_rate", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "date", "symbol", "horizon", "subset", name=op.f("pk_metrics_daily")
        ),
    )
    op.create_table(
        "module_calibration",
        sa.Column("module", sa.String(length=16), nullable=False),
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("fitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("a", sa.Float(), nullable=False),
        sa.Column("b", sa.Float(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("brier", sa.Float(), nullable=True),
        sa.Column("hit_rate", sa.Float(), nullable=True),
        sa.Column("hit_rate_ci_low", sa.Float(), nullable=True),
        sa.Column("hit_rate_ci_high", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("module", "horizon", name=op.f("pk_module_calibration")),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedup_group_id", sa.Integer(), nullable=True),
        sa.Column("is_group_head", sa.Boolean(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_items")),
        sa.UniqueConstraint("url_hash", name=op.f("uq_news_items_url_hash")),
    )
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.create_index("ix_news_items_dedup_group_id", ["dedup_group_id"], unique=False)
        batch_op.create_index("ix_news_items_published_at", ["published_at"], unique=False)

    op.create_table(
        "news_tier_metrics",
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("window", sa.String(length=8), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("hit_rate", sa.Float(), nullable=True),
        sa.Column("ci_low", sa.Float(), nullable=True),
        sa.Column("ci_high", sa.Float(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("tier", "horizon", "window", name=op.f("pk_news_tier_metrics")),
    )
    op.create_table(
        "open_interest",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("oi", sa.Float(), nullable=False),
        sa.Column("oi_value_usd", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "ts", name=op.f("pk_open_interest")),
    )
    op.create_table(
        "orderflow_1m",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("buy_vol", sa.Float(), nullable=False),
        sa.Column("sell_vol", sa.Float(), nullable=False),
        sa.Column("cvd_delta", sa.Float(), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("liq_long_usd", sa.Float(), nullable=False),
        sa.Column("liq_short_usd", sa.Float(), nullable=False),
        sa.Column("liq_count", sa.Integer(), nullable=False),
        sa.Column("top20_bid_qty", sa.Float(), nullable=True),
        sa.Column("top20_ask_qty", sa.Float(), nullable=True),
        sa.Column("top20_imbalance", sa.Float(), nullable=True),
        sa.Column("depth1pct_bid_usd", sa.Float(), nullable=True),
        sa.Column("depth1pct_ask_usd", sa.Float(), nullable=True),
        sa.Column("depth1pct_imbalance", sa.Float(), nullable=True),
        sa.Column("spread_bps", sa.Float(), nullable=True),
        sa.Column("coverage_seconds", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "ts", name=op.f("pk_orderflow_1m")),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_at", sa.Float(), nullable=False),
        sa.Column("p_up", sa.Float(), nullable=False),
        sa.Column("expected_low", sa.Float(), nullable=True),
        sa.Column("expected_high", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_label", sa.String(length=4), nullable=False),
        sa.Column("conflict", sa.Boolean(), nullable=False),
        sa.Column("veto_active", sa.Boolean(), nullable=False),
        sa.Column("veto_reason", sa.Text(), nullable=True),
        sa.Column("combined_score", sa.Float(), nullable=True),
        sa.Column("weights_json", sa.Text(), nullable=True),
        sa.Column("ensemble_version", sa.String(length=16), nullable=False),
        sa.Column("non_overlapping", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("report_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index("ix_predictions_source_run_id", ["source", "run_id"], unique=False)
        batch_op.create_index(
            "ix_predictions_symbol_horizon_as_of", ["symbol", "horizon", "as_of"], unique=False
        )
        batch_op.create_index("ix_predictions_target_at", ["target_at"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "taker_volume",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("buy_vol", sa.Float(), nullable=False),
        sa.Column("sell_vol", sa.Float(), nullable=False),
        sa.Column("ratio", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "ts", name=op.f("pk_taker_volume")),
    )
    op.create_table(
        "weekly_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("week_start", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("report_json", sa.Text(), nullable=False),
        sa.Column("summary_tr", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weekly_reports")),
        sa.UniqueConstraint("week_start", name=op.f("uq_weekly_reports_week_start")),
    )
    op.create_table(
        "weight_proposals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("current_json", sa.Text(), nullable=False),
        sa.Column("proposed_json", sa.Text(), nullable=False),
        sa.Column("based_on_n", sa.Integer(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weight_proposals")),
    )
    op.create_table(
        "weights",
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("module", sa.String(length=16), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("horizon", "module", name=op.f("pk_weights")),
    )
    op.create_table(
        "news_outcomes",
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("horizon", sa.String(length=4), nullable=False),
        sa.Column("price_at_publish", sa.Float(), nullable=False),
        sa.Column("price_after", sa.Float(), nullable=False),
        sa.Column("realized_return", sa.Float(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tier_reached", sa.Integer(), nullable=False),
        sa.Column("predicted_sign", sa.Integer(), nullable=False),
        sa.Column("hit", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_items.id"],
            name=op.f("fk_news_outcomes_news_id_news_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("news_id", "symbol", "horizon", name=op.f("pk_news_outcomes")),
    )
    op.create_table(
        "news_tier1",
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("affected_json", sa.Text(), nullable=False),
        sa.Column("tone", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("summary_tr", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("inherited_from", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_items.id"],
            name=op.f("fk_news_tier1_news_id_news_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("news_id", name=op.f("pk_news_tier1")),
    )
    op.create_table(
        "news_tier2",
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("horizon", sa.String(length=16), nullable=False),
        sa.Column("priced_in", sa.Float(), nullable=False),
        sa.Column("credibility", sa.String(length=16), nullable=False),
        sa.Column("second_order_tr", sa.Text(), nullable=True),
        sa.Column("precedent_tr", sa.Text(), nullable=True),
        sa.Column("rationale_tr", sa.Text(), nullable=True),
        sa.Column("affected_json", sa.Text(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("inherited_from", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_items.id"],
            name=op.f("fk_news_tier2_news_id_news_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("news_id", name=op.f("pk_news_tier2")),
    )
    op.create_table(
        "prediction_outcomes",
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_at_target", sa.Float(), nullable=True),
        sa.Column("realized_return", sa.Float(), nullable=True),
        sa.Column("outcome", sa.String(length=10), nullable=False),
        sa.Column("hit", sa.Boolean(), nullable=True),
        sa.Column("brier", sa.Float(), nullable=True),
        sa.Column("resolved_by", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_prediction_outcomes_prediction_id_predictions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("prediction_id", name=op.f("pk_prediction_outcomes")),
    )
    op.create_table(
        "prediction_signals",
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=False),
        sa.Column("components_json", sa.Text(), nullable=True),
        sa.Column("rationale_json", sa.Text(), nullable=True),
        sa.Column("data_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_prediction_signals_prediction_id_predictions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("prediction_id", "module", name=op.f("pk_prediction_signals")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prediction_signals")
    op.drop_table("prediction_outcomes")
    op.drop_table("news_tier2")
    op.drop_table("news_tier1")
    op.drop_table("news_outcomes")
    op.drop_table("weights")
    op.drop_table("weight_proposals")
    op.drop_table("weekly_reports")
    op.drop_table("taker_volume")
    op.drop_table("settings")
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index("ix_predictions_target_at")
        batch_op.drop_index("ix_predictions_symbol_horizon_as_of")
        batch_op.drop_index("ix_predictions_source_run_id")

    op.drop_table("predictions")
    op.drop_table("orderflow_1m")
    op.drop_table("open_interest")
    op.drop_table("news_tier_metrics")
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.drop_index("ix_news_items_published_at")
        batch_op.drop_index("ix_news_items_dedup_group_id")

    op.drop_table("news_items")
    op.drop_table("module_calibration")
    op.drop_table("metrics_daily")
    op.drop_table("macro_daily")
    op.drop_table("long_short_ratio")
    op.drop_table("llm_usage")
    op.drop_table("llm_budget_state")
    with op.batch_alter_table("liquidations", schema=None) as batch_op:
        batch_op.drop_index("ix_liquidations_symbol_ts")

    op.drop_table("liquidations")
    op.drop_table("funding_rates")
    op.drop_table("funding_live")
    op.drop_table("fear_greed")
    with op.batch_alter_table("events_outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_events_outbox_created_at")

    op.drop_table("events_outbox")
    op.drop_table("engine_heartbeat")
    op.drop_table("collector_health")
    with op.batch_alter_table("candles", schema=None) as batch_op:
        batch_op.drop_index("ix_candles_symbol_interval_close_time")

    op.drop_table("candles")
    op.drop_table("calibration_bins")
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_index("ix_calendar_events_scheduled_at")

    op.drop_table("calendar_events")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_created_at")
        batch_op.drop_index("ix_alerts_acknowledged_at")

    op.drop_table("alerts")
    # ### end Alembic commands ###
